### Author: Muhammad Shahab
### Linkedin: https://www.linkedin.com/in/muhammad-shahab-189a03265/
### Github: https://github.com/zxcoder47/AICP-Internship

### Write a NumPy program to create an array of all even integers from 30 to 70.

In [5]:
import numpy as np
integer=np.arange(30,71)
even_int=integer[integer %2==0]
print(even_int)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [6]:
random_num=np.random.rand(15)
print(random_num)

[0.98331667 0.27416232 0.91772402 0.46477961 0.83137074 0.49025456
 0.88310809 0.98829655 0.64651448 0.75774685 0.41140226 0.37820672
 0.33028676 0.21283412 0.38748753]


### How to compute the cross-product of two matrices in NumPy?

In [7]:
# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Compute the cross product
cross_product = np.cross(vector1, vector2)

print("Cross Product:", cross_product)

Cross Product: [-3  6 -3]


In [8]:
# Define two matrices
matrix1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

matrix2 = np.array([[11,12,13],
                    [14,15,16],
                    [17,18,19]])

# Compute the cross product
cross_product = np.cross(matrix1, matrix2)

print(cross_product)

[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


### How to compute the determinant of an array using NumPy?

In [9]:
# Define an array
array = np.array([[11, 12],
                  [3, 4]])

# Compute the determinant
determinant = np.linalg.det(array)

print(determinant)

8.000000000000002


### How to create a 3x3x3 array with random values using NumPy?

In [10]:
# Create a 3x3x3 array with random values
array = np.random.rand(3, 3, 3)

print(array)

[[[0.65103799 0.13800219 0.60748552]
  [0.30202774 0.48901201 0.79041225]
  [0.70728396 0.43931401 0.56869643]]

 [[0.37266683 0.38742339 0.85019534]
  [0.2143963  0.86661756 0.1152766 ]
  [0.91212854 0.31972265 0.62818511]]

 [[0.93744127 0.23841683 0.6015892 ]
  [0.81562333 0.24529223 0.86528168]
  [0.90876822 0.85901174 0.27893971]]]


### How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

In [11]:
# Create a 5x5 array with random values
array = np.random.rand(5, 5)

# Find the minimum and maximum values
minimum_value = np.min(array)
maximum_value = np.max(array)

print("Array:")
print(array)
print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)

Array:
[[0.56128579 0.71383599 0.34844423 0.51601547 0.73974531]
 [0.5325017  0.12070742 0.32472314 0.89545873 0.17081194]
 [0.99627876 0.54315458 0.22748222 0.69998577 0.70932405]
 [0.62696763 0.70407844 0.13292486 0.54340932 0.18887213]
 [0.48241856 0.9225947  0.10597762 0.15693608 0.83782704]]
Minimum value: 0.10597762408969746
Maximum value: 0.9962787590026225


### How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [12]:
# Define the array
array = np.array([[11, 12, 13],
                  [4, 5, 6]])

# Compute the mean, standard deviation, and variance along the second axis
mean_values = np.mean(array, axis=1)
variance_values = np.var(array, axis=1)
std_values = np.std(array, axis=1)


print("Array:")
print(array)
print("Mean along the second axis:", mean_values)
print("Variance along the second axis:", variance_values)
print("Standard deviation along the second axis:", std_values)

Array:
[[11 12 13]
 [ 4  5  6]]
Mean along the second axis: [12.  5.]
Standard deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
